apiVersion: v1
kind: Service
metadata:
  labels:
    app: hse-todolist
  name: hse-todolist
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hse-todolist
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
