apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hftk8s
  name: hftk8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hftk8s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hftk8s
    spec:
      containers:
      - image: maeddes/k8shft:v3
        name: hftk8s
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {}
status: {}
