apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hftk8s
  name: hftk8s
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hftk8s
  type: LoadBalancer
status:
  loadBalancer: {}
