apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hse-todoui
  name: hse-todoui
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: hse-todoui
  type: LoadBalancer
status:
  loadBalancer: {}
